import { Asset, ActionItem, DocumentItem, EstateData } from '../types/estate';

const BASE_URL = 'http://localhost:8000';

const getHeaders = () => ({
  'Authorization': `Bearer ${localStorage.getItem('jwt')}`
});

const getEstateId = () => localStorage.getItem('current_estate_id');

export const getEstateMap = async () => {
  const eid = getEstateId();
  if (!eid) return null;
  const res = await fetch(`${BASE_URL}/estates/${eid}/estate-map`, { headers: getHeaders() });
  if (!res.ok) return null;
  return res.json();
};

export const downloadEstateReport = async (): Promise<void> => {
  const eid = getEstateId();
  if (!eid) throw new Error('No estate ID found');
  const reportWindow = window.open('', '_blank');
  const res = await fetch(`${BASE_URL}/estates/${eid}/report`, { headers: getHeaders() });
  if (!res.ok) {
    reportWindow?.close();
    throw new Error('Unable to create the estate report');
  }
  const report = await res.json();
  if (!reportWindow) throw new Error('Please allow pop-ups to print the estate report');

  const escapeHtml = (value: unknown) => String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
  const currency = (value: unknown) => {
    const amount = Number(value);
    return Number.isFinite(amount) ? `₹${amount.toLocaleString('en-IN')}` : 'Not available';
  };
  const assets = report.assets.map((asset: any) => `
    <article class="item">
      <div><strong>${escapeHtml(asset.institution || 'Unnamed asset')}</strong><span>${escapeHtml(asset.category)}</span></div>
      <div class="value">${currency(asset.estimated_value)}</div>
      <p>${escapeHtml(asset.next_step || 'No next step recorded')}</p>
      <ul>${(asset.requirements || []).map((req: any) => `<li class="${req.complete ? 'complete' : ''}">${req.complete ? 'Complete' : 'Pending'}: ${escapeHtml(req.name)}</li>`).join('')}</ul>
    </article>`).join('');
  const actions = report.actions.map((action: any) => `
    <li><strong>${escapeHtml(action.title || 'Untitled action')}</strong> <span>${escapeHtml(action.status)}${action.urgency ? ` · ${escapeHtml(action.urgency)}` : ''}</span></li>`).join('');

  reportWindow.document.write(`<!doctype html><html><head><title>${escapeHtml(report.deceased_name || 'Estate')} report</title><style>
    @page { margin: 18mm; } body { font-family: Georgia, serif; color: #172033; max-width: 900px; margin: 0 auto; line-height: 1.5; }
    header { border-bottom: 3px solid #0f766e; padding-bottom: 18px; margin-bottom: 24px; } h1 { margin: 0 0 4px; font-size: 30px; } h2 { margin-top: 28px; color: #0f766e; border-bottom: 1px solid #cbd5e1; padding-bottom: 6px; }
    .meta { color: #64748b; } .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; } .stat { background: #f1f5f9; padding: 12px; } .stat strong { display: block; font-size: 20px; } .item { border-bottom: 1px solid #e2e8f0; padding: 12px 0; break-inside: avoid; } .item div:first-child { display: flex; justify-content: space-between; gap: 16px; } .item span, li { color: #475569; } .value { font-weight: bold; } ul { margin: 6px 0 0; padding-left: 20px; } .complete { color: #0f766e; } footer { margin-top: 30px; font-size: 12px; color: #64748b; }
    @media print { .no-print { display: none; } }
  </style></head><body>
    <header><h1>${escapeHtml(report.deceased_name || 'Estate')} Estate Report</h1><div class="meta">Status: ${escapeHtml(report.status)} · Generated: ${escapeHtml(new Date(report.generated_at).toLocaleString())}</div></header>
    <section class="summary"><div class="stat"><strong>${escapeHtml(report.summary.asset_count)}</strong>Assets</div><div class="stat"><strong>${currency(report.summary.estimated_total_value)}</strong>Estimated value</div><div class="stat"><strong>${escapeHtml(report.summary.action_count)}</strong>Actions</div><div class="stat"><strong>${escapeHtml(report.summary.requirements_remaining)}</strong>Requirements pending</div></section>
    <h2>Assets</h2>${assets || '<p>No assets recorded.</p>'}
    <h2>Actions</h2>${actions ? `<ul>${actions}</ul>` : '<p>No actions recorded.</p>'}
    <footer>Generated by EstateClear · Clarity in estate management.</footer>
  </body></html>`);
  reportWindow.document.close();
  reportWindow.focus();
  reportWindow.setTimeout(() => reportWindow.print(), 250);
};

export const getEstate = async (): Promise<EstateData> => {
  const data = await getEstateMap();
  if (!data) return { ownerName: null, completionPercentage: 0 };

  const summary = data.summary || {};
  const totalTasks = Math.max(1, (summary.critical_tasks_remaining || 0) + (summary.documents_needed || 0) + (summary.assets_found || 0));
  const completionPercentage = Math.max(0, Math.min(100, Math.round((1 - ((summary.critical_tasks_remaining || 0) + (summary.documents_needed || 0)) / totalTasks) * 100)));

  return {
    ownerName: data.deceased_name,
    completionPercentage: Number.isFinite(completionPercentage) ? completionPercentage : 0
  };
};

export const getAssets = async (): Promise<Asset[]> => {
  const data = await getEstateMap();
  if (!data || !data.assets) return [];

  return data.assets
    .filter((a: any) => a.category !== 'action_item')
    .map((a: any) => {
      const uiStatus = a.status === 'in_progress' ? 'In progress' : a.status === 'done' ? 'Done' : 'Action needed';
      const apiReqs = a.requirements || [];
      const requirements = apiReqs.map((r: any) => ({
        id: r.id,
        name: r.doc_type,
        completed: r.is_satisfied
      }));
      const knowledge = [
        `Category: ${a.category}`,
        `Institution: ${a.institution_name || 'Unknown'}`,
        `Identifier: ${a.reference_number || 'Unknown'}`
      ];
      return {
        id: a.id,
        category: a.category,
        provider: a.institution_name || 'Unknown',
        amount: parseFloat(a.estimated_value || '0'),
        status: uiStatus,
        knowledge,
        requirements,
        documents: (a.documents || []).map((document: any) => ({
          id: document.id,
          name: document.name,
          status: document.status === 'Uploaded' ? 'Uploaded' : 'Missing'
        }))
      };
    });
};

export const getAssetById = async (id: string): Promise<Asset | undefined> => {
  const assets = await getAssets();
  return assets.find(a => a.id === id);
};

export const getActions = async (): Promise<ActionItem[]> => {
  const data = await getEstateMap();
  if (!data || !data.assets) return [];

  const actions: ActionItem[] = [];
  data.assets.forEach((a: any) => {
    if (a.next_step_text) {
      const uiStatus = a.status === 'in_progress' ? 'In progress' : a.status === 'done' ? 'Done' : 'Needs attention';
      actions.push({
        id: a.id,
        title: a.next_step_text,
        description: a.category === 'action_item' ? 'Detected from documents' : `Related to ${a.institution_name}`,
        status: uiStatus,
        assetId: a.category === 'action_item' ? undefined : a.id
      });
    }
  });
  return actions;
};

export const getDocuments = async (): Promise<DocumentItem[]> => {
  const eid = getEstateId();
  if (!eid) return [];

  const res = await fetch(`${BASE_URL}/estates/${eid}/documents`, { headers: getHeaders() });
  if (!res.ok) return [];

  const docs = await res.json();
  return docs.map((doc: any) => ({
    id: doc.id,
    name: doc.name,
    status: doc.status,           
    processing_error: doc.processing_error,
    assetId: doc.asset_id || undefined,
    uploadedAt: doc.uploaded_at || undefined
  }));
};

export interface ClosureState {
  status: 'active' | 'closing' | 'closed';
  ready: boolean;
  pending_actions: number;
  pending_documents: number;
  schedule?: ClosureSchedule | null;
}

export interface ClosureSchedule {
  id: string;
  scheduled_for: string;
  status: 'scheduled' | 'cancelled' | 'executed';
  deletion_reason?: string;
}

export const getClosureState = async (): Promise<ClosureState | null> => {
  const eid = getEstateId();
  if (!eid) return null;
  const res = await fetch(`${BASE_URL}/estates/${eid}/closure`, { headers: getHeaders() });
  if (!res.ok) return null;
  return res.json();
};

export const closeEstate = async (): Promise<ClosureState> => {
  const eid = getEstateId();
  if (!eid) throw new Error('No estate ID found');
  const res = await fetch(`${BASE_URL}/estates/${eid}/closure`, {
    method: 'POST',
    headers: getHeaders()
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.detail || 'Estate cannot be closed yet');
  return data;
};

const closureMutation = async (method: 'POST' | 'PATCH' | 'DELETE', path: string, body?: object) => {
  const eid = getEstateId();
  if (!eid) throw new Error('No estate ID found');
  const res = await fetch(`${BASE_URL}/estates/${eid}/closure${path}`, {
    method,
    headers: body ? { 'Content-Type': 'application/json', ...getHeaders() } : getHeaders(),
    body: body ? JSON.stringify(body) : undefined
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.detail || 'Unable to update deletion schedule');
  return data;
};

export const scheduleEstateDeletion = (scheduledFor: string, confirmText: string) =>
  closureMutation('POST', '/schedule', { scheduled_for: scheduledFor, confirm_text: confirmText });

export const rescheduleEstateDeletion = (scheduledFor: string, confirmText: string) =>
  closureMutation('PATCH', '/schedule', { scheduled_for: scheduledFor, confirm_text: confirmText });

export const cancelEstateDeletion = () => closureMutation('DELETE', '/schedule');

export const deleteEstateNow = (confirmText: string) =>
  closureMutation('POST', '/delete-now', { scheduled_for: new Date().toISOString(), confirm_text: confirmText });

export const askEstateQuestion = async (question: string): Promise<string> => {
  const eid = getEstateId();
  if (!eid) throw new Error('No estate ID found');
  const res = await fetch(`${BASE_URL}/estates/${eid}/ask`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders() },
    body: JSON.stringify({ question })
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.detail || 'Unable to answer that question right now');
  return data.answer;
};

export interface DocumentExplanation {
  what_it_is: string;
  what_we_found: string[];
  what_is_missing: string;
  next_steps: string;
}

export const explainDocument = async (documentId: string): Promise<DocumentExplanation> => {
  const eid = getEstateId();
  if (!eid) throw new Error('No estate ID found');
  const res = await fetch(`${BASE_URL}/estates/${eid}/documents/${documentId}/explain`, { headers: getHeaders() });
  const data = await res.json();
  if (!res.ok) throw new Error(data.detail || 'Unable to explain this document right now');
  return data;
};

export const uploadDocument = async (file: File): Promise<void> => {
  const eid = getEstateId();
  if (!eid) throw new Error('No estate ID found');

  const formData = new FormData();
  formData.append('file', file);

  const res = await fetch(`${BASE_URL}/estates/${eid}/documents`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${localStorage.getItem('jwt')}`
    },
    body: formData
  });

  if (!res.ok) {
    const error = await res.json();
    throw new Error(error.detail || 'Upload failed');
  }
};

export const updateActionStatus = async (id: string, status: ActionItem['status']): Promise<void> => {
  const eid = getEstateId();
  if (!eid) return;
  const normalizedStatus = status === 'Needs attention' ? 'Action needed' : status === 'In progress' ? 'In progress' : 'Done';
  const res = await fetch(`${BASE_URL}/estates/${eid}/assets/${id}`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders() },
    body: JSON.stringify({ status: normalizedStatus })
  });
  if (!res.ok) throw new Error('Unable to update action status');
};

export const completeRequirement = async (assetId: string, reqId: string, status: boolean): Promise<void> => {
  const eid = getEstateId();
  if (!eid) return;
  await fetch(`${BASE_URL}/estates/${eid}/assets/${assetId}/requirements/${reqId}`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders() },
    body: JSON.stringify({ is_satisfied: status })
  });
};

export const resetState = async (): Promise<void> => {
  localStorage.removeItem('current_estate_id');
};
